import {
  defineText,
  fallback,
  reviewed,
  type LocalizedText,
} from '@/lib/i18n';

export const ADVICE_ENTRY_COPY = {
  title: defineText({
    en: reviewed('Ask a health question'),
    zh: reviewed('咨询健康问题'),
    bo: fallback('zh'),
  }),
  subtitle: defineText({
    en: reviewed('General suggestions from Chinese, Tibetan, and Western medicine — not a diagnosis.'),
    zh: reviewed('来自中医、藏医、西医的一般性建议——不是诊断。'),
    bo: fallback('zh'),
  }),
} as const satisfies Record<string, LocalizedText>;

export const ADVICE_FORM_COPY = {
  homeLabel: defineText({
    en: reviewed('Back to home'),
    zh: reviewed('返回首页'),
    bo: fallback('zh'),
  }),
  genderLabel: defineText({
    en: reviewed('Gender'),
    zh: reviewed('性别'),
    bo: fallback('zh'),
  }),
  ageLabel: defineText({
    en: reviewed('Age'),
    zh: reviewed('年龄'),
    bo: fallback('zh'),
  }),
  questionLabel: defineText({
    en: reviewed('Your health question'),
    zh: reviewed('您的健康问题'),
    bo: fallback('zh'),
  }),
  questionPlaceholder: defineText({
    en: reviewed('Describe what is happening and what you would like to understand.'),
    zh: reviewed('请描述目前的情况，以及您想了解的问题。'),
    bo: fallback('zh'),
  }),
  answerLanguageLabel: defineText({
    en: reviewed('Answer language'),
    zh: reviewed('回答语言'),
    bo: fallback('zh'),
  }),
  preferNotToSay: defineText({
    en: reviewed('Prefer not to say · 不便透露'),
    zh: reviewed('Prefer not to say · 不便透露'),
    bo: fallback('zh'),
  }),
  female: defineText({
    en: reviewed('Female · 女'),
    zh: reviewed('Female · 女'),
    bo: fallback('zh'),
  }),
  male: defineText({
    en: reviewed('Male · 男'),
    zh: reviewed('Male · 男'),
    bo: fallback('zh'),
  }),
  under18: defineText({
    en: reviewed('Under 18 · 18 岁以下'),
    zh: reviewed('Under 18 · 18 岁以下'),
    bo: fallback('zh'),
  }),
  age18To64: defineText({
    en: reviewed('18–64 · 18–64 岁'),
    zh: reviewed('18–64 · 18–64 岁'),
    bo: fallback('zh'),
  }),
  age65AndOver: defineText({
    en: reviewed('65 and over · 65 岁及以上'),
    zh: reviewed('65 and over · 65 岁及以上'),
    bo: fallback('zh'),
  }),
  english: defineText({
    en: reviewed('English'),
    zh: reviewed('英文'),
    bo: fallback('zh'),
  }),
  chinese: defineText({
    en: reviewed('Chinese'),
    zh: reviewed('中文'),
    bo: fallback('zh'),
  }),
  submit: defineText({
    en: reviewed('Ask my question'),
    zh: reviewed('提交问题'),
    bo: fallback('zh'),
  }),
  loading: defineText({
    en: reviewed('Checking availability'),
    zh: reviewed('正在检查功能是否可用'),
    bo: fallback('zh'),
  }),
  loadingNote: defineText({
    en: reviewed('The three perspectives will appear here when the protected answer service is available.'),
    zh: reviewed('安全回答服务开放后，三个医学视角的内容将显示在这里。'),
    bo: fallback('zh'),
  }),
  tibetanAnswerLanguages: defineText({
    en: reviewed('Answers are available in Chinese and English only for now. Chinese is selected by default.'),
    zh: reviewed('目前回答仅提供中文和英文，默认选择中文。'),
    bo: fallback('zh'),
  }),
} as const satisfies Record<string, LocalizedText>;

export const ADVICE_UNAVAILABLE_COPY = {
  heading: defineText({
    en: reviewed('Health suggestions are not available yet.'),
    zh: reviewed('健康建议功能暂不可用。'),
    bo: fallback('zh'),
  }),
  body: defineText({
    en: reviewed('The page is ready, but the answer service will stay unavailable until its safety checks are in place.'),
    zh: reviewed('页面已经准备好，但在安全检查机制就绪之前，回答服务不会开放。'),
    bo: fallback('zh'),
  }),
} as const satisfies Record<string, LocalizedText>;

export const ADVICE_DISCLAIMERS = [
  defineText({
    en: reviewed('This page offers general health suggestions generated by AI, from three medical traditions. They are starting points to discuss with a professional — not a diagnosis or a treatment plan for you.'),
    zh: reviewed('本页面提供由 AI 生成的一般性健康建议，来自三种医学传统。它们是供您与专业人员讨论的参考，不是针对您个人的诊断或治疗方案。'),
    bo: fallback('zh'),
  }),
  defineText({
    en: reviewed('The AI can be wrong, even when it sounds confident. No person reviews these answers before you see them.'),
    zh: reviewed('AI 可能出错，即使听起来很有把握。回答在您看到之前没有经过人工审核。'),
    bo: fallback('zh'),
  }),
  defineText({
    en: reviewed('We never provide medication doses. For any medicine or remedy — including herbal and traditional ones — and how much to take, ask a doctor or pharmacist.'),
    zh: reviewed('我们一律不提供用药剂量。任何药物（包括中药、藏药等传统药物）的品种与用量，请咨询医生或药师。'),
    bo: fallback('zh'),
  }),
  defineText({
    en: reviewed('The Chinese-medicine and Tibetan-medicine perspectives reflect traditional practice, not modern clinical-trial evidence.'),
    zh: reviewed('中医与藏医视角反映的是传统实践，而非现代临床试验证据。'),
    bo: fallback('zh'),
  }),
  defineText({
    en: reviewed("If symptoms are severe or getting worse quickly, don't wait for an answer here — in mainland China call 120; elsewhere call your local emergency number."),
    zh: reviewed('如症状严重或迅速加重，请不要等待本页回答——中国大陆请拨打 120，其他地区请拨打当地急救电话。'),
    bo: fallback('zh'),
  }),
] as const satisfies readonly LocalizedText[];

export const ADVICE_REFERRAL = defineText({
  en: reviewed('These are general suggestions to bring to a professional — not a diagnosis or treatment plan for you. Please discuss anything you plan to act on with a doctor, and see a doctor promptly if symptoms persist or worsen.'),
  zh: reviewed('以上只是供您与专业人员讨论的一般性建议，不是针对您个人的诊断或治疗方案。任何打算实际采取的做法，请先与医生讨论；如症状持续或加重，请及时就医。'),
  bo: fallback('zh'),
});

export const ADVICE_SCHOOL_COPY = {
  tcm: {
    label: defineText({
      en: reviewed('Chinese Medicine'),
      zh: reviewed('中医'),
      bo: fallback('zh'),
    }),
    subtitle: defineText({
      en: reviewed('A traditional Chinese medicine perspective — based on traditional practice and theory, not on modern clinical-trial evidence.'),
      zh: reviewed('中医视角——基于传统实践与理论，而非现代临床试验证据。'),
      bo: fallback('zh'),
    }),
  },
  tibetan: {
    label: defineText({
      en: reviewed('Tibetan Medicine'),
      zh: reviewed('藏医'),
      bo: fallback('zh'),
    }),
    subtitle: defineText({
      en: reviewed('A traditional Tibetan medicine perspective — based on traditional practice and theory, not on modern clinical-trial evidence.'),
      zh: reviewed('藏医视角——基于传统实践与理论，而非现代临床试验证据。'),
      bo: fallback('zh'),
    }),
  },
  western: {
    label: defineText({
      en: reviewed('Western Medicine'),
      zh: reviewed('西医'),
      bo: fallback('zh'),
    }),
    subtitle: defineText({
      en: reviewed('General information from mainstream medicine — still general, not a diagnosis for you.'),
      zh: reviewed('现代医学的一般性信息——仍属一般信息，不是针对您的诊断。'),
      bo: fallback('zh'),
    }),
  },
} as const satisfies Record<
  string,
  Readonly<{ label: LocalizedText; subtitle: LocalizedText }>
>;
