// INDEPENDENT GOLD LABELS for the real corpora (Codex should-fix #7).
//
// WHY: r6Coverage and confidentlyWrong were SELF-GRADED, and the self-grading hid the thing they
// were introduced to find. r6Coverage's denominator was `row.entry?.highStakes` — OUR table. An
// analyte we fail to NAME has entry === null, so it dropped out of the numerator AND the
// denominator: it did not score 0, it became invisible. The metric therefore reported a
// comfortable "80% of high-stakes rows confirmed" while Lactate, Free (ionized) Calcium, the
// blood gases (pH/pO2/pCO2/Base Excess), INR(PT), Glucose and Urea Nitrogen were not being counted
// at all, because we don't recognise them. A metric whose denominator is chosen by the system
// under test cannot measure that system's blind spots.
//
// WHAT THIS IS: one label per DISTINCT ROW NAME as printed in the corpora (227 of them, covering
// all 465 rows). Lookup is EXACT-MATCH on the verbatim trimmed name — deliberately NOT through
// findEntry()/our alias index, because routing gold labels through the matcher being graded would
// reintroduce the same circularity.
//
// HOW THEY WERE MADE (and what that does and does not buy):
//  - 3+ independent labelers per name (227 names, 2-11 votes each, 929 raw label records), each
//    told explicitly NOT to read data/reference-labs.ts, lib/ or validation/ — so the labels are
//    independent of the CODE THEY GRADE, which is the gameability axis that matters here.
//  - Inter-rater agreement 93.0% (211/227 unanimous on kind AND highStakes). The 16 disputed names
//    were adjudicated separately with the criteria "when genuinely torn, prefer TRUE", since
//    under-calling high-stakes is the dangerous direction for a safety metric.
//  - HONEST LIMIT: these labels are independent of our implementation, NOT independent of model
//    knowledge — they were authored by LLM labelers, not by a clinician or a citable standards
//    document. They are strong enough to expose recognition blind spots (their purpose) and should
//    NOT be treated as clinical ground truth. Replacing them with a clinician-reviewed or
//    published critical-value list is the obvious upgrade.
//
// 'kind' separates a real coverage failure from correct behaviour: 29 of these names are
// non-analytes (ventilator settings, specimen metadata, opaque codes like UTX1, free-text
// descriptors). Declining to interpret those is CORRECT, and lumping them into an abstain-rate
// made the app look worse than it is.

export interface GoldLabel {
  name: string; // verbatim row label as printed in the corpus
  kind: 'analyte' | 'non-analyte';
  highStakes: boolean; // an abnormal result plausibly demands prompt clinical action
  canonical: string; // short canonical test name ('' for non-analytes)
}

export const GOLD_LABELS: GoldLabel[] = [
  { name: 'Glucose', kind: 'analyte', highStakes: true, canonical: 'Blood glucose' },
  { name: 'Potassium', kind: 'analyte', highStakes: true, canonical: 'Potassium' },
  { name: 'Sodium', kind: 'analyte', highStakes: true, canonical: 'Sodium (serum/plasma)' },
  { name: 'Chloride', kind: 'analyte', highStakes: true, canonical: 'Chloride' },
  { name: 'Anion Gap', kind: 'analyte', highStakes: true, canonical: 'Anion gap (serum)' },
  { name: 'Bicarbonate', kind: 'analyte', highStakes: true, canonical: 'Bicarbonate (serum total CO2)' },
  { name: 'Urea Nitrogen', kind: 'analyte', highStakes: true, canonical: 'Blood urea nitrogen' },
  { name: 'Creatinine', kind: 'analyte', highStakes: true, canonical: 'Serum creatinine' },
  { name: 'Hematocrit', kind: 'analyte', highStakes: true, canonical: 'Hematocrit' },
  { name: 'Hemoglobin', kind: 'analyte', highStakes: true, canonical: 'Hemoglobin' },
  { name: 'pH', kind: 'analyte', highStakes: true, canonical: 'pH (blood gas pH when in a blood-gas context, ref 7.35-7.45; urine pH when in a urinalysis context, ref 5-8)' },
  { name: 'Magnesium', kind: 'analyte', highStakes: true, canonical: 'Magnesium (serum)' },
  { name: 'MCV', kind: 'analyte', highStakes: false, canonical: 'Mean corpuscular volume' },
  { name: 'White Blood Cells', kind: 'analyte', highStakes: true, canonical: 'White blood cell count' },
  { name: 'MCH', kind: 'analyte', highStakes: false, canonical: 'Mean corpuscular hemoglobin' },
  { name: 'RDW', kind: 'analyte', highStakes: false, canonical: 'Red cell distribution width' },
  { name: 'Platelet Count', kind: 'analyte', highStakes: true, canonical: 'Platelet count' },
  { name: 'Red Blood Cells', kind: 'analyte', highStakes: true, canonical: 'Red blood cell count' },
  { name: 'MCHC', kind: 'analyte', highStakes: false, canonical: 'Mean corpuscular hemoglobin concentration' },
  { name: 'Calculated Total CO2', kind: 'analyte', highStakes: true, canonical: 'Total carbon dioxide (serum bicarbonate)' },
  { name: 'Specimen Type', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: 'pO2', kind: 'analyte', highStakes: true, canonical: 'Blood gas partial pressure of oxygen' },
  { name: 'pCO2', kind: 'analyte', highStakes: true, canonical: 'Blood gas partial pressure of carbon dioxide' },
  { name: 'Base Excess', kind: 'analyte', highStakes: true, canonical: 'Base excess (blood gas)' },
  { name: 'Phosphate', kind: 'analyte', highStakes: true, canonical: 'Serum phosphate' },
  { name: 'Calcium, Total', kind: 'analyte', highStakes: true, canonical: 'Total serum calcium' },
  { name: 'Intubated', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: 'Lactate', kind: 'analyte', highStakes: true, canonical: 'Blood lactate' },
  { name: 'Free Calcium', kind: 'analyte', highStakes: true, canonical: 'Ionized calcium' },
  { name: 'Length of Urine Collection', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: 'Oxygen', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: 'RDW-SD', kind: 'analyte', highStakes: false, canonical: 'Red cell distribution width, standard deviation' },
  { name: 'PT', kind: 'analyte', highStakes: true, canonical: 'Prothrombin time' },
  { name: 'Bilirubin', kind: 'analyte', highStakes: false, canonical: 'Bilirubin (urine dipstick bilirubin in urinalysis context)' },
  { name: 'Specific Gravity', kind: 'analyte', highStakes: false, canonical: 'Urine specific gravity' },
  { name: 'Ketone', kind: 'analyte', highStakes: true, canonical: 'Urine ketones' },
  { name: 'Urobilinogen', kind: 'analyte', highStakes: false, canonical: 'Urine urobilinogen' },
  { name: 'Leukocytes', kind: 'analyte', highStakes: false, canonical: 'Urine leukocyte esterase' },
  { name: 'Nitrite', kind: 'analyte', highStakes: false, canonical: 'Urine nitrite' },
  { name: 'Protein', kind: 'analyte', highStakes: false, canonical: 'Urine protein' },
  { name: 'Urine Color', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: 'Urine Appearance', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: 'Blood', kind: 'analyte', highStakes: false, canonical: 'Urine occult blood (dipstick)' },
  { name: 'Ventilation Rate', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: 'RBC', kind: 'analyte', highStakes: true, canonical: 'Red blood cell count' },
  { name: 'WBC', kind: 'analyte', highStakes: true, canonical: 'White blood cell count (blood count, or urine microscopy WBC when #/hpf)' },
  { name: 'INR(PT)', kind: 'analyte', highStakes: true, canonical: 'International normalized ratio' },
  { name: 'Temperature', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: 'PEEP', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: 'Tidal Volume', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: 'I', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: 'L', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: 'H', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: '单核细胞百分比', kind: 'analyte', highStakes: false, canonical: 'Monocyte percentage' },
  { name: '嗜酸性粒细胞百分比', kind: 'analyte', highStakes: false, canonical: 'Eosinophil percentage' },
  { name: '嗜碱性粒细胞百分比', kind: 'analyte', highStakes: false, canonical: 'Basophil percentage' },
  { name: '淋巴细胞数', kind: 'analyte', highStakes: true, canonical: 'Absolute lymphocyte count' },
  { name: '谷丙转氨酶', kind: 'analyte', highStakes: false, canonical: 'Alanine aminotransferase' },
  { name: '谷草转氨酶', kind: 'analyte', highStakes: false, canonical: 'Aspartate aminotransferase' },
  { name: '碱性磷酸酶', kind: 'analyte', highStakes: false, canonical: 'Alkaline phosphatase' },
  { name: '谷酰转肽酶', kind: 'analyte', highStakes: false, canonical: 'Gamma-glutamyl transferase (GGT)' },
  { name: '直接胆红素', kind: 'analyte', highStakes: false, canonical: 'Direct bilirubin' },
  { name: 'Uhold', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: 'Urine tube, held', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: 'UTX4', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: 'Cocaine, Urine', kind: 'analyte', highStakes: true, canonical: 'Urine cocaine screen' },
  { name: 'UTX7', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: 'Methadone, Urine', kind: 'analyte', highStakes: true, canonical: 'Urine methadone screen' },
  { name: 'Benzodiazepine Screen, Urine', kind: 'analyte', highStakes: true, canonical: 'Benzodiazepine screen, urine' },
  { name: 'Oxycodone', kind: 'analyte', highStakes: true, canonical: 'Oxycodone' },
  { name: 'UTX3', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: 'UTX1', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: 'UTX2', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: 'Opiate Screen, Urine', kind: 'analyte', highStakes: true, canonical: 'Opiate screen, urine' },
  { name: 'UTX6', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: 'UTX5', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: 'Amphetamine Screen, Urine', kind: 'analyte', highStakes: true, canonical: 'Urine amphetamine screen' },
  { name: 'Barbiturate Screen, Urine', kind: 'analyte', highStakes: true, canonical: 'Urine barbiturate screen' },
  { name: '% Hemoglobin A1c', kind: 'analyte', highStakes: false, canonical: 'Hemoglobin A1c' },
  { name: 'eAG', kind: 'analyte', highStakes: false, canonical: 'Estimated average glucose' },
  { name: 'Cholesterol, HDL', kind: 'analyte', highStakes: false, canonical: 'HDL cholesterol' },
  { name: 'Triglycerides', kind: 'analyte', highStakes: false, canonical: 'Triglycerides' },
  { name: 'Cholesterol, Total', kind: 'analyte', highStakes: false, canonical: 'Total cholesterol' },
  { name: 'Cholesterol, LDL, Calculated', kind: 'analyte', highStakes: false, canonical: 'LDL cholesterol (calculated)' },
  { name: 'Cholesterol Ratio (Total/HDL)', kind: 'analyte', highStakes: false, canonical: 'Total cholesterol to HDL ratio' },
  { name: 'Yeast', kind: 'analyte', highStakes: false, canonical: 'Urine microscopy yeast' },
  { name: 'Bacteria', kind: 'analyte', highStakes: false, canonical: 'Urine microscopy bacteria' },
  { name: 'Amorphous Crystals', kind: 'analyte', highStakes: false, canonical: 'Urine microscopy amorphous crystals' },
  { name: 'Epithelial Cells', kind: 'analyte', highStakes: false, canonical: 'Urine microscopy epithelial cells' },
  { name: 'Ventilator', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: 'Sodium, Whole Blood', kind: 'analyte', highStakes: true, canonical: 'Whole blood sodium' },
  { name: 'Chloride, Whole Blood', kind: 'analyte', highStakes: false, canonical: 'Whole blood chloride' },
  { name: 'Hematocrit, Calculated', kind: 'analyte', highStakes: true, canonical: 'Hematocrit (calculated)' },
  { name: 'Potassium, Whole Blood', kind: 'analyte', highStakes: true, canonical: 'Whole blood potassium' },
  { name: 'Assist/Control', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: 'Alkaline Phosphatase', kind: 'analyte', highStakes: false, canonical: 'Alkaline phosphatase' },
  { name: 'Asparate Aminotransferase (AST)', kind: 'analyte', highStakes: false, canonical: 'Aspartate aminotransferase (AST)' },
  { name: 'Alanine Aminotransferase (ALT)', kind: 'analyte', highStakes: false, canonical: 'Alanine aminotransferase (ALT)' },
  { name: 'Lipase', kind: 'analyte', highStakes: true, canonical: 'Serum lipase' },
  { name: 'Amylase', kind: 'analyte', highStakes: true, canonical: 'Serum amylase' },
  { name: 'Bilirubin, Total', kind: 'analyte', highStakes: true, canonical: 'Total bilirubin' },
  { name: 'PTT', kind: 'analyte', highStakes: true, canonical: 'Partial thromboplastin time' },
  { name: 'Troponin T', kind: 'analyte', highStakes: true, canonical: 'Cardiac troponin T' },
  { name: 'Thyroid Stimulating Hormone', kind: 'analyte', highStakes: false, canonical: 'Thyroid stimulating hormone' },
  { name: 'Estimated GFR (MDRD equation)', kind: 'analyte', highStakes: true, canonical: 'Estimated glomerular filtration rate' },
  { name: 'PT%', kind: 'analyte', highStakes: true, canonical: 'Prothrombin activity percentage' },
  { name: 'INR', kind: 'analyte', highStakes: true, canonical: 'International normalized ratio' },
  { name: 'APTT', kind: 'analyte', highStakes: true, canonical: 'Activated partial thromboplastin time' },
  { name: 'Fib', kind: 'analyte', highStakes: true, canonical: 'Fibrinogen' },
  { name: 'TT', kind: 'analyte', highStakes: true, canonical: 'Thrombin time' },
  { name: 'D-Dimer', kind: 'analyte', highStakes: true, canonical: 'D-dimer' },
  { name: '肌钙蛋白I', kind: 'analyte', highStakes: true, canonical: 'Cardiac troponin I' },
  { name: '肌红蛋白', kind: 'analyte', highStakes: true, canonical: 'Myoglobin' },
  { name: '肌酸激酶同工酶质量', kind: 'analyte', highStakes: true, canonical: 'CK-MB mass' },
  { name: '乙肝病毒表面 抗原', kind: 'analyte', highStakes: false, canonical: 'Hepatitis B surface antigen (HBsAg)' },
  { name: '人类免疫缺陷 病毒抗体/抗原 (P24)', kind: 'analyte', highStakes: true, canonical: 'HIV antigen/antibody (p24)' },
  { name: '梅毒螺旋体特 异性抗体', kind: 'analyte', highStakes: false, canonical: 'Treponema pallidum specific antibody' },
  { name: '丙型肝炎病毒 lgG抗体', kind: 'analyte', highStakes: false, canonical: 'Hepatitis C virus IgG antibody' },
  { name: 'A磁珠法高灵敏乙肝病毒(HBV)DNA定量检测', kind: 'analyte', highStakes: false, canonical: 'Hepatitis B virus DNA quantitation' },
  { name: '反应蛋白', kind: 'analyte', highStakes: false, canonical: 'C-reactive protein' },
  { name: '血小板压积', kind: 'analyte', highStakes: false, canonical: 'Plateletcrit' },
  { name: '红蛋白', kind: 'analyte', highStakes: true, canonical: 'Hemoglobin' },
  { name: 'HCT', kind: 'analyte', highStakes: true, canonical: 'Hematocrit' },
  { name: '中性粒细胞百分比', kind: 'analyte', highStakes: false, canonical: 'Neutrophil percentage' },
  { name: '淋巴细胞百分比', kind: 'analyte', highStakes: false, canonical: 'Lymphocyte percentage' },
  { name: '[细胞平均体积', kind: 'analyte', highStakes: false, canonical: 'Mean corpuscular volume (MCV)' },
  { name: '均血红蛋白里', kind: 'analyte', highStakes: false, canonical: 'Mean corpuscular hemoglobin (MCH)' },
  { name: '均血红蛋白浓度', kind: 'analyte', highStakes: false, canonical: 'Mean corpuscular hemoglobin concentration (MCHC)' },
  { name: '中性粒细胞数', kind: 'analyte', highStakes: true, canonical: 'Absolute neutrophil count' },
  { name: '[细胞分布宽度SD', kind: 'analyte', highStakes: false, canonical: 'Red cell distribution width, standard deviation' },
  { name: '单核细胞数', kind: 'analyte', highStakes: false, canonical: 'Absolute monocyte count' },
  { name: '[细胞分布宽度CV', kind: 'analyte', highStakes: false, canonical: 'Red cell distribution width, coefficient of variation' },
  { name: '嗜酸性粒细胞数', kind: 'analyte', highStakes: false, canonical: 'Absolute eosinophil count' },
  { name: '镉(Cd)', kind: 'analyte', highStakes: true, canonical: 'Blood cadmium' },
  { name: '铅(Pb)', kind: 'analyte', highStakes: true, canonical: 'Blood lead' },
  { name: '铜(Cu)', kind: 'analyte', highStakes: false, canonical: 'Blood copper' },
  { name: '铁(Fe)', kind: 'analyte', highStakes: false, canonical: 'Blood iron (trace element)' },
  { name: '锌(Zn)', kind: 'analyte', highStakes: false, canonical: 'Blood zinc' },
  { name: '钙(Ca)', kind: 'analyte', highStakes: true, canonical: 'Blood calcium (trace element panel)' },
  { name: '镁(Mg)', kind: 'analyte', highStakes: true, canonical: 'Blood magnesium (trace element panel)' },
  { name: '颜色', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: '外观', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: '白细胞', kind: 'analyte', highStakes: false, canonical: 'Urine leukocyte esterase (dipstick)' },
  { name: '亚硝酸盐', kind: 'analyte', highStakes: false, canonical: 'Urine nitrite' },
  { name: '尿胆原', kind: 'analyte', highStakes: false, canonical: 'Urine urobilinogen' },
  { name: '蛋白质', kind: 'analyte', highStakes: false, canonical: 'Urine protein' },
  { name: '酸碱度', kind: 'analyte', highStakes: false, canonical: 'Urine pH' },
  { name: '隐血', kind: 'analyte', highStakes: false, canonical: 'Urine occult blood' },
  { name: '比重', kind: 'analyte', highStakes: false, canonical: 'Urine specific gravity' },
  { name: '酮体', kind: 'analyte', highStakes: true, canonical: 'Urine ketones' },
  { name: '胆红素', kind: 'analyte', highStakes: false, canonical: 'Urine bilirubin (dipstick)' },
  { name: '葡萄糖', kind: 'analyte', highStakes: false, canonical: 'Urine glucose (dipstick)' },
  { name: '抗坏血酸', kind: 'analyte', highStakes: false, canonical: 'Urine ascorbic acid' },
  { name: '镜检红细胞', kind: 'analyte', highStakes: false, canonical: 'Urine microscopy red blood cells' },
  { name: '镜检白细胞', kind: 'analyte', highStakes: false, canonical: 'Urine microscopy white blood cells' },
  { name: '上皮细胞', kind: 'analyte', highStakes: false, canonical: 'Urine microscopy epithelial cells' },
  { name: '管型', kind: 'analyte', highStakes: false, canonical: 'Urine microscopy casts' },
  { name: '结晶', kind: 'analyte', highStakes: false, canonical: 'Urine microscopy crystals' },
  { name: '促甲状腺激 素受体抗体', kind: 'analyte', highStakes: false, canonical: 'TSH receptor antibody' },
  { name: '游离三碘甲 状原氨酸', kind: 'analyte', highStakes: false, canonical: 'Free triiodothyronine (FT3)' },
  { name: '游离甲状腺 素', kind: 'analyte', highStakes: false, canonical: 'Free thyroxine (FT4)' },
  { name: '促甲状腺激 素', kind: 'analyte', highStakes: false, canonical: 'Thyroid stimulating hormone' },
  { name: '细胞量', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: '标本满意度', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: '诊断意见', kind: 'non-analyte', highStakes: false, canonical: '' },
  { name: '白蛋白', kind: 'analyte', highStakes: false, canonical: 'Albumin' },
  { name: '乙型肝炎表 面抗原定量', kind: 'analyte', highStakes: false, canonical: 'Hepatitis B surface antigen (quantitative)' },
  { name: '乙型肝炎表 面抗体定量', kind: 'analyte', highStakes: false, canonical: 'Hepatitis B surface antibody (quantitative)' },
  { name: '乙型肝炎e抗 原定量', kind: 'analyte', highStakes: false, canonical: 'Hepatitis B e antigen (quantitative)' },
  { name: '乙型肝炎e抗 体定量', kind: 'analyte', highStakes: false, canonical: 'Hepatitis B e antibody (quantitative)' },
  { name: '乙型肝炎核 心抗体定量', kind: 'analyte', highStakes: false, canonical: 'Hepatitis B core antibody (quantitative)' },
  { name: '氯', kind: 'analyte', highStakes: false, canonical: 'Chloride' },
  { name: '乳酸脱氢酶', kind: 'analyte', highStakes: false, canonical: 'Lactate dehydrogenase' },
  { name: '总胆红素', kind: 'analyte', highStakes: false, canonical: 'Total bilirubin' },
  { name: '胆碱酯酶', kind: 'analyte', highStakes: false, canonical: 'Cholinesterase' },
  { name: '总胆汁酸', kind: 'analyte', highStakes: false, canonical: 'Total bile acids' },
  { name: '亮氨酸氨酞酶', kind: 'analyte', highStakes: false, canonical: 'Leucine aminopeptidase' },
  { name: '腺苷脱氨酶', kind: 'analyte', highStakes: false, canonical: 'Adenosine deaminase' },
  { name: '间接胆红素', kind: 'analyte', highStakes: false, canonical: 'Indirect bilirubin' },
  { name: '尿素', kind: 'analyte', highStakes: true, canonical: 'Blood urea nitrogen' },
  { name: '肌酐', kind: 'analyte', highStakes: true, canonical: 'Creatinine' },
  { name: '尿酸', kind: 'analyte', highStakes: false, canonical: 'Uric acid' },
  { name: 'β2微球蛋白', kind: 'analyte', highStakes: false, canonical: 'Beta-2 microglobulin' },
  { name: '血糖', kind: 'analyte', highStakes: true, canonical: 'Blood glucose' },
  { name: '凝血酶时间(TT)', kind: 'analyte', highStakes: true, canonical: 'Thrombin time' },
  { name: '凝血酶原时间(PT)', kind: 'analyte', highStakes: true, canonical: 'Prothrombin time' },
  { name: '活化部分凝血活酶(APTT)', kind: 'analyte', highStakes: true, canonical: 'Activated partial thromboplastin time' },
  { name: '纤维蛋白原(FIB)', kind: 'analyte', highStakes: true, canonical: 'Fibrinogen' },
  { name: 'PT国际标准比值(INR)', kind: 'analyte', highStakes: true, canonical: 'INR' },
  { name: '中性细胞比率', kind: 'analyte', highStakes: false, canonical: 'Neutrophil percentage' },
  { name: '淋巴细胞比率', kind: 'analyte', highStakes: false, canonical: 'Lymphocyte percentage' },
  { name: '中性细胞值', kind: 'analyte', highStakes: true, canonical: 'Absolute neutrophil count' },
  { name: '嗜酸性粒细胞计数', kind: 'analyte', highStakes: false, canonical: 'Absolute eosinophil count' },
  { name: '嗜碱性粒细胞计数', kind: 'analyte', highStakes: false, canonical: 'Absolute basophil count' },
  { name: '红细胞计数', kind: 'analyte', highStakes: false, canonical: 'Red blood cell count' },
  { name: '血红蛋白', kind: 'analyte', highStakes: true, canonical: 'Hemoglobin' },
  { name: '红细胞压积', kind: 'analyte', highStakes: true, canonical: 'Hematocrit' },
  { name: '甲胎蛋白', kind: 'analyte', highStakes: false, canonical: 'Alpha-fetoprotein' },
  { name: '癌胚抗原', kind: 'analyte', highStakes: false, canonical: 'Carcinoembryonic antigen' },
  { name: '糖类抗原199', kind: 'analyte', highStakes: false, canonical: 'CA 19-9' },
  { name: '糖类抗原125', kind: 'analyte', highStakes: false, canonical: 'CA 125' },
  { name: '糖类抗原15-3', kind: 'analyte', highStakes: false, canonical: 'CA 15-3' },
  { name: 'ACTH促肾上腺皮质激素', kind: 'analyte', highStakes: false, canonical: 'Adrenocorticotropic hormone' },
  { name: 'B型钠尿肽', kind: 'analyte', highStakes: true, canonical: 'B-type natriuretic peptide' },
  { name: '超敏C-反应蛋白', kind: 'analyte', highStakes: false, canonical: 'High-sensitivity C-reactive protein' },
  { name: 'a-淀粉酶', kind: 'analyte', highStakes: true, canonical: 'Alpha-amylase' },
  { name: 'DOB', kind: 'analyte', highStakes: false, canonical: 'Urea breath test delta over baseline (H. pylori)' },
  { name: '滴虫', kind: 'analyte', highStakes: false, canonical: 'Trichomonas (vaginal wet mount)' },
  { name: '霉菌', kind: 'analyte', highStakes: false, canonical: 'Fungi/yeast (vaginal wet mount)' },
  { name: '清洁度', kind: 'analyte', highStakes: false, canonical: 'Vaginal cleanliness grade' },
  { name: '细菌性阴道病', kind: 'analyte', highStakes: false, canonical: 'Bacterial vaginosis test' },
  { name: 'HPV低危亚型61', kind: 'analyte', highStakes: false, canonical: 'HPV low-risk type 61' },
  { name: 'HPV高危亚型16', kind: 'analyte', highStakes: false, canonical: 'HPV high-risk type 16' },
  { name: 'HPV高危亚型18', kind: 'analyte', highStakes: false, canonical: 'HPV high-risk type 18' },
  { name: 'HPV低危亚型42', kind: 'analyte', highStakes: false, canonical: 'HPV low-risk type 42' },
  { name: 'HPV高危亚型31', kind: 'analyte', highStakes: false, canonical: 'HPV high-risk type 31' },
  { name: 'HPV高危亚型52', kind: 'analyte', highStakes: false, canonical: 'HPV high-risk type 52' },
  { name: 'HPV高危亚型58', kind: 'analyte', highStakes: false, canonical: 'HPV high-risk type 58' },
  { name: '01(rs4244285,G>A) 01(rs4244285,G>A)', kind: 'analyte', highStakes: false, canonical: 'CYP2C19*2 (rs4244285) genotype' },
  { name: '02(rs4986893,G>A) 02(rs4986893,G>A)', kind: 'analyte', highStakes: false, canonical: 'CYP2C19*3 (rs4986893) genotype' },
  { name: '60(rs12248560,C>T) 60(rs12248560,C>T)', kind: 'analyte', highStakes: false, canonical: 'CYP2C19*17 (rs12248560) genotype' },
  { name: '成熟淋巴细胞群', kind: 'analyte', highStakes: false, canonical: 'Mature lymphocyte population (flow cytometry)' },
  { name: '髓系原始细胞群', kind: 'analyte', highStakes: true, canonical: 'Myeloid blast population (flow cytometry)' },
  { name: '中性粒细胞群', kind: 'analyte', highStakes: false, canonical: 'Neutrophil population (flow cytometry)' },
  { name: '单核细胞群', kind: 'analyte', highStakes: false, canonical: 'Monocyte population (flow cytometry)' },
  { name: '有核红细胞群', kind: 'analyte', highStakes: false, canonical: 'Nucleated red cell population (flow cytometry)' },
  { name: 'TRBC1阳性率', kind: 'analyte', highStakes: false, canonical: 'TRBC1 positivity rate (flow cytometry)' },
];

const INDEX = new Map(GOLD_LABELS.map((g) => [g.name.trim(), g]));

/** Exact-match lookup on the printed name. Never goes through our alias index — that is the point. */
export function goldFor(rawName: string): GoldLabel | null {
  return INDEX.get(rawName.trim()) ?? null;
}
