// REAL US lab-report rows — a deterministic sample of the public MIMIC-IV Clinical Database
// Demo v2.2 (https://physionet.org/content/mimic-iv-demo/2.2/, Open Data Commons ODbL v1.0;
// real de-identified US hospital labs, Beth Israel Deaconess Medical Center, Boston). This is
// the BEACHHEAD corpus (US-diaspora decision): US analyte names + conventional units, replacing
// the Chinese/SI MedRepBench set for the beachhead measurement. Externally authored — we do NOT
// author rows. Sampling: panels grouped by (subject,hadm,charttime), sizes 6-24, chosen by
// lowest stable FNV hash (non-cherry-picked). is_abnormal derives from MIMIC's own 'flag'.
// Attribution: Johnson, A. et al. MIMIC-IV Clinical Database Demo (v2.2). PhysioNet (2023).
import type { RealReport } from './sample';

export const MIMIC_US_SAMPLE: RealReport[] = [
  {
    image: 'mimic-10035185|22580999|2120-05-12 14:00:00',
    kind: 'US hospital panel',
    items: [
      { item_name: 'Glucose', item_value: '', item_unit: 'mg/dL', item_range: '', is_abnormal: '0' },
      { item_name: 'Bilirubin', item_value: '', item_unit: 'mg/dL', item_range: '', is_abnormal: '0' },
      { item_name: 'Specific Gravity', item_value: '1.046', item_unit: '', item_range: '1.001-1.035', is_abnormal: '1' },
      { item_name: 'pH', item_value: '6.5', item_unit: 'units', item_range: '5-8', is_abnormal: '0' },
      { item_name: 'Ketone', item_value: '', item_unit: 'mg/dL', item_range: '', is_abnormal: '0' },
      { item_name: 'Urobilinogen', item_value: '', item_unit: 'mg/dL', item_range: '0.2-1', is_abnormal: '0' },
      { item_name: 'Leukocytes', item_value: '', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Nitrite', item_value: '', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Protein', item_value: '', item_unit: 'mg/dL', item_range: '', is_abnormal: '0' },
      { item_name: 'Urine Color', item_value: '', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Urine Appearance', item_value: '', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Blood', item_value: '', item_unit: '', item_range: '', is_abnormal: '0' },
    ],
  },
  {
    image: 'mimic-10023117|28887654|2174-12-18 06:50:00',
    kind: 'US hospital panel',
    items: [
      { item_name: 'Hematocrit', item_value: '', item_unit: '%', item_range: '40-51', is_abnormal: '0' },
      { item_name: 'Potassium', item_value: '4.1', item_unit: 'mEq/L', item_range: '3.3-5.1', is_abnormal: '0' },
      { item_name: 'Glucose', item_value: '75', item_unit: 'mg/dL', item_range: '70-100', is_abnormal: '0' },
      { item_name: 'Anion Gap', item_value: '20', item_unit: 'mEq/L', item_range: '8-20', is_abnormal: '0' },
      { item_name: 'Sodium', item_value: '142', item_unit: 'mEq/L', item_range: '133-145', is_abnormal: '0' },
      { item_name: 'Bicarbonate', item_value: '22', item_unit: 'mEq/L', item_range: '22-32', is_abnormal: '0' },
      { item_name: 'Chloride', item_value: '104', item_unit: 'mEq/L', item_range: '96-108', is_abnormal: '0' },
      { item_name: 'Urea Nitrogen', item_value: '47', item_unit: 'mg/dL', item_range: '6-20', is_abnormal: '1' },
      { item_name: 'Magnesium', item_value: '2.1', item_unit: 'mg/dL', item_range: '1.6-2.6', is_abnormal: '0' },
      { item_name: 'Creatinine', item_value: '2.3', item_unit: 'mg/dL', item_range: '0.5-1.2', is_abnormal: '1' },
    ],
  },
  {
    image: 'mimic-10026406||2133-03-01 17:13:00',
    kind: 'US hospital panel',
    items: [
      { item_name: 'Uhold', item_value: 'HOLD.', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Length of Urine Collection', item_value: '', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Length of Urine Collection', item_value: '', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Length of Urine Collection', item_value: '', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Urine tube, held', item_value: 'HOLD.  SPECIMEN TO BE HELD 48 HOURS AND DISCARDED.', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'UTX4', item_value: '-595', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Cocaine, Urine', item_value: '', item_unit: 'N/A', item_range: '', is_abnormal: '0' },
      { item_name: 'UTX7', item_value: '-398', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Methadone, Urine', item_value: '', item_unit: 'N/A', item_range: '', is_abnormal: '0' },
      { item_name: 'Benzodiazepine Screen, Urine', item_value: '', item_unit: 'N/A', item_range: '', is_abnormal: '0' },
      { item_name: 'Oxycodone', item_value: '', item_unit: 'N/A', item_range: '', is_abnormal: '0' },
      { item_name: 'UTX3', item_value: '0', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'UTX1', item_value: '-91', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'UTX2', item_value: '-780', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Opiate Screen, Urine', item_value: '', item_unit: 'N/A', item_range: '', is_abnormal: '0' },
      { item_name: 'UTX6', item_value: '-71', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'UTX5', item_value: '407', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Amphetamine Screen, Urine', item_value: '', item_unit: 'N/A', item_range: '', is_abnormal: '1' },
      { item_name: 'Barbiturate Screen, Urine', item_value: '', item_unit: 'N/A', item_range: '', is_abnormal: '0' },
    ],
  },
  {
    image: 'mimic-10039708|28258130|2140-01-27 09:49:00',
    kind: 'US hospital panel',
    items: [
      { item_name: 'Calculated Total CO2', item_value: '19', item_unit: 'mEq/L', item_range: '21-30', is_abnormal: '1' },
      { item_name: 'Intubated', item_value: 'NOT INTUBATED.', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'pH', item_value: '7.36', item_unit: 'units', item_range: '7.35-7.45', is_abnormal: '0' },
      { item_name: 'Specimen Type', item_value: 'ART.', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'pO2', item_value: '60', item_unit: 'mm Hg', item_range: '85-105', is_abnormal: '1' },
      { item_name: 'Lactate', item_value: '3.4', item_unit: 'mmol/L', item_range: '0.5-2', is_abnormal: '1' },
      { item_name: 'Oxygen', item_value: '60', item_unit: '%', item_range: '', is_abnormal: '0' },
      { item_name: 'pCO2', item_value: '33', item_unit: 'mm Hg', item_range: '35-45', is_abnormal: '1' },
      { item_name: 'Ventilation Rate', item_value: '/25.', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Base Excess', item_value: '-5', item_unit: 'mEq/L', item_range: '', is_abnormal: '0' },
    ],
  },
  {
    image: 'mimic-10005866|27167814|2148-03-15 12:34:00',
    kind: 'US hospital panel',
    items: [
      { item_name: 'MCV', item_value: '105', item_unit: 'fL', item_range: '82-98', is_abnormal: '1' },
      { item_name: 'White Blood Cells', item_value: '9.5', item_unit: 'K/uL', item_range: '4-10', is_abnormal: '0' },
      { item_name: 'MCH', item_value: '35.3', item_unit: 'pg', item_range: '26-32', is_abnormal: '1' },
      { item_name: 'RDW', item_value: '16.7', item_unit: '%', item_range: '10.5-15.5', is_abnormal: '1' },
      { item_name: 'Platelet Count', item_value: '144', item_unit: 'K/uL', item_range: '150-400', is_abnormal: '1' },
      { item_name: 'Red Blood Cells', item_value: '2.38', item_unit: 'm/uL', item_range: '4.6-6.1', is_abnormal: '1' },
      { item_name: 'Hematocrit', item_value: '25', item_unit: '%', item_range: '40-51', is_abnormal: '1' },
      { item_name: 'MCHC', item_value: '33.6', item_unit: 'g/dL', item_range: '32-37', is_abnormal: '0' },
      { item_name: 'RDW-SD', item_value: '61.4', item_unit: 'fL', item_range: '35.1-46.3', is_abnormal: '1' },
      { item_name: 'Hemoglobin', item_value: '8.4', item_unit: 'g/dL', item_range: '13.7-17.5', is_abnormal: '1' },
    ],
  },
  {
    image: 'mimic-10023239||2136-08-31 13:05:00',
    kind: 'US hospital panel',
    items: [
      { item_name: '% Hemoglobin A1c', item_value: '10', item_unit: '%', item_range: '4.8-5.9', is_abnormal: '1' },
      { item_name: 'eAG', item_value: '240', item_unit: 'mg/dL', item_range: '91-123', is_abnormal: '1' },
      { item_name: 'Hematocrit', item_value: '38.5', item_unit: '%', item_range: '36-48', is_abnormal: '0' },
      { item_name: 'Red Blood Cells', item_value: '4.39', item_unit: 'm/uL', item_range: '4.2-5.4', is_abnormal: '0' },
      { item_name: 'Hemoglobin', item_value: '13.3', item_unit: 'g/dL', item_range: '12-16', is_abnormal: '0' },
      { item_name: 'RDW', item_value: '12.2', item_unit: '%', item_range: '10.5-15.5', is_abnormal: '0' },
      { item_name: 'White Blood Cells', item_value: '6.5', item_unit: 'K/uL', item_range: '4-11', is_abnormal: '0' },
      { item_name: 'MCHC', item_value: '34.7', item_unit: '%', item_range: '31-35', is_abnormal: '0' },
      { item_name: 'MCH', item_value: '30.4', item_unit: 'pg', item_range: '27-32', is_abnormal: '0' },
      { item_name: 'MCV', item_value: '88', item_unit: 'fL', item_range: '82-98', is_abnormal: '0' },
      { item_name: 'Platelet Count', item_value: '188', item_unit: 'K/uL', item_range: '150-440', is_abnormal: '0' },
      { item_name: 'Cholesterol, HDL', item_value: '84', item_unit: 'mg/dL', item_range: '', is_abnormal: '0' },
      { item_name: 'Triglycerides', item_value: '45', item_unit: 'mg/dL', item_range: '0-149', is_abnormal: '0' },
      { item_name: 'Cholesterol, Total', item_value: '257', item_unit: 'mg/dL', item_range: '0-199', is_abnormal: '1' },
      { item_name: 'Cholesterol, LDL, Calculated', item_value: '164', item_unit: 'mg/dL', item_range: '0-129', is_abnormal: '1' },
      { item_name: 'Cholesterol Ratio (Total/HDL)', item_value: '3.1', item_unit: 'Ratio', item_range: '', is_abnormal: '0' },
    ],
  },
  {
    image: 'mimic-10015860||2187-12-14 14:21:00',
    kind: 'US hospital panel',
    items: [
      { item_name: 'Protein', item_value: '30', item_unit: 'mg/dL', item_range: '', is_abnormal: '0' },
      { item_name: 'Yeast', item_value: 'NONE', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'RBC', item_value: '', item_unit: '#/hpf', item_range: '0-2', is_abnormal: '0' },
      { item_name: 'Ketone', item_value: '', item_unit: 'mg/dL', item_range: '', is_abnormal: '0' },
      { item_name: 'Urine Color', item_value: '', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Leukocytes', item_value: '', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Specific Gravity', item_value: '1.015', item_unit: '', item_range: '1.001-1.035', is_abnormal: '0' },
      { item_name: 'Glucose', item_value: '1000', item_unit: 'mg/dL', item_range: '', is_abnormal: '0' },
      { item_name: 'Nitrite', item_value: '', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Bilirubin', item_value: '', item_unit: 'mg/dL', item_range: '', is_abnormal: '0' },
      { item_name: 'Blood', item_value: '', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'pH', item_value: '5.5', item_unit: 'units', item_range: '5-8', is_abnormal: '0' },
      { item_name: 'Bacteria', item_value: '', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'WBC', item_value: '', item_unit: '#/hpf', item_range: '0-5', is_abnormal: '0' },
      { item_name: 'Amorphous Crystals', item_value: '', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Urobilinogen', item_value: '', item_unit: 'mg/dL', item_range: '0.2-1', is_abnormal: '0' },
      { item_name: 'Epithelial Cells', item_value: '0', item_unit: '#/hpf', item_range: '', is_abnormal: '0' },
      { item_name: 'Urine Appearance', item_value: '', item_unit: '', item_range: '', is_abnormal: '0' },
    ],
  },
  {
    image: 'mimic-10015931|28157142|2176-11-25 07:50:00',
    kind: 'US hospital panel',
    items: [
      { item_name: 'INR(PT)', item_value: '3.4', item_unit: '', item_range: '0.9-1.1', is_abnormal: '1' },
      { item_name: 'PT', item_value: '38.5', item_unit: 'sec', item_range: '9.4-12.5', is_abnormal: '1' },
      { item_name: 'Potassium', item_value: '5.1', item_unit: 'mEq/L', item_range: '3.3-5.1', is_abnormal: '0' },
      { item_name: 'Chloride', item_value: '89', item_unit: 'mEq/L', item_range: '96-108', is_abnormal: '1' },
      { item_name: 'Bicarbonate', item_value: '27', item_unit: 'mEq/L', item_range: '22-32', is_abnormal: '0' },
      { item_name: 'Urea Nitrogen', item_value: '60', item_unit: 'mg/dL', item_range: '6-20', is_abnormal: '1' },
      { item_name: 'Creatinine', item_value: '3.1', item_unit: 'mg/dL', item_range: '0.5-1.2', is_abnormal: '1' },
      { item_name: 'Anion Gap', item_value: '15', item_unit: 'mEq/L', item_range: '8-20', is_abnormal: '0' },
      { item_name: 'Sodium', item_value: '126', item_unit: 'mEq/L', item_range: '133-145', is_abnormal: '1' },
    ],
  },
  {
    image: 'mimic-10016742|27568122|2178-07-24 05:08:00',
    kind: 'US hospital panel',
    items: [
      { item_name: 'Oxygen', item_value: '40', item_unit: '%', item_range: '', is_abnormal: '0' },
      { item_name: 'Intubated', item_value: 'INTUBATED.', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Temperature', item_value: '36.4', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'PEEP', item_value: '5', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Ventilation Rate', item_value: '14/.', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Specimen Type', item_value: 'VEN.', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Tidal Volume', item_value: '400', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'pO2', item_value: '36', item_unit: 'mm Hg', item_range: '85-105', is_abnormal: '1' },
      { item_name: 'Base Excess', item_value: '2', item_unit: 'mEq/L', item_range: '', is_abnormal: '0' },
      { item_name: 'Lactate', item_value: '0.8', item_unit: 'mmol/L', item_range: '0.5-2', is_abnormal: '0' },
      { item_name: 'Calculated Total CO2', item_value: '28', item_unit: 'mEq/L', item_range: '21-30', is_abnormal: '0' },
      { item_name: 'pCO2', item_value: '39', item_unit: 'mm Hg', item_range: '35-45', is_abnormal: '0' },
      { item_name: 'Free Calcium', item_value: '1.18', item_unit: 'mmol/L', item_range: '1.12-1.32', is_abnormal: '0' },
      { item_name: 'pH', item_value: '7.45', item_unit: 'units', item_range: '7.35-7.45', is_abnormal: '0' },
    ],
  },
  {
    image: 'mimic-10004422|21255400|2111-01-17 13:54:00',
    kind: 'US hospital panel',
    items: [
      { item_name: 'Ventilator', item_value: 'CONTROLLED.', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Intubated', item_value: 'INTUBATED.', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Specimen Type', item_value: 'ART.', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Sodium, Whole Blood', item_value: '131', item_unit: 'mEq/L', item_range: '133-145', is_abnormal: '1' },
      { item_name: 'Chloride, Whole Blood', item_value: '107', item_unit: 'mEq/L', item_range: '96-108', is_abnormal: '0' },
      { item_name: 'Hemoglobin', item_value: '7.5', item_unit: 'g/dL', item_range: '14-18', is_abnormal: '1' },
      { item_name: 'pCO2', item_value: '42', item_unit: 'mm Hg', item_range: '35-45', is_abnormal: '0' },
      { item_name: 'Base Excess', item_value: '0', item_unit: 'mEq/L', item_range: '', is_abnormal: '0' },
      { item_name: 'Glucose', item_value: '210', item_unit: 'mg/dL', item_range: '70-105', is_abnormal: '1' },
      { item_name: 'Lactate', item_value: '2.8', item_unit: 'mmol/L', item_range: '0.5-2', is_abnormal: '1' },
      { item_name: 'Free Calcium', item_value: '1.16', item_unit: 'mmol/L', item_range: '1.12-1.32', is_abnormal: '0' },
      { item_name: 'Hematocrit, Calculated', item_value: '23', item_unit: '%', item_range: '', is_abnormal: '0' },
      { item_name: 'Potassium, Whole Blood', item_value: '4.9', item_unit: 'mEq/L', item_range: '3.3-5.1', is_abnormal: '0' },
      { item_name: 'Calculated Total CO2', item_value: '25', item_unit: 'mEq/L', item_range: '21-30', is_abnormal: '0' },
      { item_name: 'pH', item_value: '7.37', item_unit: 'units', item_range: '7.35-7.45', is_abnormal: '0' },
      { item_name: 'pO2', item_value: '374', item_unit: 'mm Hg', item_range: '85-105', is_abnormal: '1' },
    ],
  },
  {
    image: 'mimic-10037975|27617929|2185-01-21 18:53:00',
    kind: 'US hospital panel',
    items: [
      { item_name: 'Oxygen', item_value: '50', item_unit: '%', item_range: '', is_abnormal: '0' },
      { item_name: 'Intubated', item_value: 'INTUBATED.', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Specimen Type', item_value: 'VEN.', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Temperature', item_value: '37.7', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Assist/Control', item_value: '', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'PEEP', item_value: '16', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Tidal Volume', item_value: '450', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'pH', item_value: '7.29', item_unit: 'units', item_range: '7.35-7.45', is_abnormal: '1' },
      { item_name: 'pCO2', item_value: '50', item_unit: 'mm Hg', item_range: '35-45', is_abnormal: '1' },
      { item_name: 'pO2', item_value: '55', item_unit: 'mm Hg', item_range: '85-105', is_abnormal: '1' },
      { item_name: 'Calculated Total CO2', item_value: '25', item_unit: 'mEq/L', item_range: '21-30', is_abnormal: '0' },
      { item_name: 'Base Excess', item_value: '-2', item_unit: 'mEq/L', item_range: '', is_abnormal: '0' },
    ],
  },
  {
    image: 'mimic-10021487|27660781|2117-03-05 05:30:00',
    kind: 'US hospital panel',
    items: [
      { item_name: 'MCHC', item_value: '29.9', item_unit: '%', item_range: '31-35', is_abnormal: '1' },
      { item_name: 'Hemoglobin', item_value: '8.7', item_unit: 'g/dL', item_range: '14-18', is_abnormal: '1' },
      { item_name: 'RDW', item_value: '16', item_unit: '%', item_range: '10.5-15.5', is_abnormal: '1' },
      { item_name: 'Platelet Count', item_value: '369', item_unit: 'K/uL', item_range: '150-440', is_abnormal: '0' },
      { item_name: 'White Blood Cells', item_value: '4.8', item_unit: 'K/uL', item_range: '4-11', is_abnormal: '0' },
      { item_name: 'MCH', item_value: '24.8', item_unit: 'pg', item_range: '27-32', is_abnormal: '1' },
      { item_name: 'Red Blood Cells', item_value: '3.51', item_unit: 'm/uL', item_range: '4.6-6.2', is_abnormal: '1' },
      { item_name: 'MCV', item_value: '83', item_unit: 'fL', item_range: '82-98', is_abnormal: '0' },
      { item_name: 'Hematocrit', item_value: '29.2', item_unit: '%', item_range: '40-52', is_abnormal: '1' },
      { item_name: 'Anion Gap', item_value: '11', item_unit: 'mEq/L', item_range: '8-20', is_abnormal: '0' },
      { item_name: 'Alkaline Phosphatase', item_value: '83', item_unit: 'IU/L', item_range: '40-130', is_abnormal: '0' },
      { item_name: 'Asparate Aminotransferase (AST)', item_value: '15', item_unit: 'IU/L', item_range: '0-40', is_abnormal: '0' },
      { item_name: 'Bicarbonate', item_value: '26', item_unit: 'mEq/L', item_range: '22-32', is_abnormal: '0' },
      { item_name: 'Potassium', item_value: '3.7', item_unit: 'mEq/L', item_range: '3.3-5.1', is_abnormal: '0' },
      { item_name: 'Chloride', item_value: '100', item_unit: 'mEq/L', item_range: '96-108', is_abnormal: '0' },
      { item_name: 'Urea Nitrogen', item_value: '2', item_unit: 'mg/dL', item_range: '6-20', is_abnormal: '1' },
      { item_name: 'Alanine Aminotransferase (ALT)', item_value: '7', item_unit: 'IU/L', item_range: '0-40', is_abnormal: '0' },
      { item_name: 'Lipase', item_value: '190', item_unit: 'IU/L', item_range: '0-60', is_abnormal: '1' },
      { item_name: 'Sodium', item_value: '133', item_unit: 'mEq/L', item_range: '133-145', is_abnormal: '0' },
      { item_name: 'Amylase', item_value: '218', item_unit: 'IU/L', item_range: '0-100', is_abnormal: '1' },
      { item_name: 'Bilirubin, Total', item_value: '0.5', item_unit: 'mg/dL', item_range: '0-1.5', is_abnormal: '0' },
      { item_name: 'Glucose', item_value: '139', item_unit: 'mg/dL', item_range: '70-100', is_abnormal: '1' },
      { item_name: 'Creatinine', item_value: '0.4', item_unit: 'mg/dL', item_range: '0.5-1.2', is_abnormal: '1' },
    ],
  },
  {
    image: 'mimic-10015931|24420677|2176-12-20 14:45:00',
    kind: 'US hospital panel',
    items: [
      { item_name: 'I', item_value: '1', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Creatinine', item_value: '1.7', item_unit: 'mg/dL', item_range: '0.5-1.2', is_abnormal: '1' },
      { item_name: 'Phosphate', item_value: '3.7', item_unit: 'mg/dL', item_range: '2.7-4.5', is_abnormal: '0' },
      { item_name: 'Bicarbonate', item_value: '37', item_unit: 'mEq/L', item_range: '22-32', is_abnormal: '1' },
      { item_name: 'Urea Nitrogen', item_value: '38', item_unit: 'mg/dL', item_range: '6-20', is_abnormal: '1' },
      { item_name: 'L', item_value: '6', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Anion Gap', item_value: '11', item_unit: 'mEq/L', item_range: '8-20', is_abnormal: '0' },
      { item_name: 'Sodium', item_value: '131', item_unit: 'mEq/L', item_range: '133-145', is_abnormal: '1' },
      { item_name: 'Glucose', item_value: '379', item_unit: 'mg/dL', item_range: '70-100', is_abnormal: '1' },
      { item_name: 'Potassium', item_value: '4.3', item_unit: 'mEq/L', item_range: '3.3-5.1', is_abnormal: '0' },
      { item_name: 'Calcium, Total', item_value: '8.8', item_unit: 'mg/dL', item_range: '8.4-10.3', is_abnormal: '0' },
      { item_name: 'H', item_value: '17', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Chloride', item_value: '87', item_unit: 'mEq/L', item_range: '96-108', is_abnormal: '1' },
      { item_name: 'Magnesium', item_value: '1.9', item_unit: 'mg/dL', item_range: '1.6-2.6', is_abnormal: '0' },
    ],
  },
  {
    image: 'mimic-10037861|24256866|2115-10-13 13:28:00',
    kind: 'US hospital panel',
    items: [
      { item_name: 'Phosphate', item_value: '2.9', item_unit: 'mg/dL', item_range: '2.7-4.5', is_abnormal: '0' },
      { item_name: 'Calcium, Total', item_value: '8.9', item_unit: 'mg/dL', item_range: '8.4-10.3', is_abnormal: '0' },
      { item_name: 'Creatinine', item_value: '1.6', item_unit: 'mg/dL', item_range: '0.5-1.2', is_abnormal: '1' },
      { item_name: 'Magnesium', item_value: '2.4', item_unit: 'mg/dL', item_range: '1.6-2.6', is_abnormal: '0' },
      { item_name: 'Chloride', item_value: '91', item_unit: 'mEq/L', item_range: '96-108', is_abnormal: '1' },
      { item_name: 'Urea Nitrogen', item_value: '30', item_unit: 'mg/dL', item_range: '6-20', is_abnormal: '1' },
      { item_name: 'Glucose', item_value: '323', item_unit: 'mg/dL', item_range: '70-100', is_abnormal: '1' },
      { item_name: 'Potassium', item_value: '4.6', item_unit: 'mEq/L', item_range: '3.3-5.1', is_abnormal: '0' },
      { item_name: 'Sodium', item_value: '139', item_unit: 'mEq/L', item_range: '133-145', is_abnormal: '0' },
      { item_name: 'Anion Gap', item_value: '13', item_unit: 'mEq/L', item_range: '8-20', is_abnormal: '0' },
      { item_name: 'Bicarbonate', item_value: '40', item_unit: 'mEq/L', item_range: '22-32', is_abnormal: '1' },
    ],
  },
  {
    image: 'mimic-10021487|28998349|2116-12-11 02:00:00',
    kind: 'US hospital panel',
    items: [
      { item_name: 'Specimen Type', item_value: 'ART.', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'pO2', item_value: '108', item_unit: 'mm Hg', item_range: '85-105', is_abnormal: '1' },
      { item_name: 'Base Excess', item_value: '5', item_unit: 'mEq/L', item_range: '', is_abnormal: '0' },
      { item_name: 'Glucose', item_value: '125', item_unit: 'mg/dL', item_range: '70-105', is_abnormal: '1' },
      { item_name: 'pCO2', item_value: '53', item_unit: 'mm Hg', item_range: '35-45', is_abnormal: '1' },
      { item_name: 'pH', item_value: '7.4', item_unit: 'units', item_range: '7.35-7.45', is_abnormal: '0' },
      { item_name: 'Free Calcium', item_value: '1.13', item_unit: 'mmol/L', item_range: '1.12-1.32', is_abnormal: '0' },
      { item_name: 'Calculated Total CO2', item_value: '34', item_unit: 'mEq/L', item_range: '21-30', is_abnormal: '1' },
    ],
  },
  {
    image: 'mimic-10012853|26369609|2175-04-08 06:07:00',
    kind: 'US hospital panel',
    items: [
      { item_name: 'MCH', item_value: '24.4', item_unit: 'pg', item_range: '27-32', is_abnormal: '1' },
      { item_name: 'Red Blood Cells', item_value: '4.18', item_unit: 'm/uL', item_range: '4.2-5.4', is_abnormal: '1' },
      { item_name: 'Hematocrit', item_value: '34.9', item_unit: '%', item_range: '36-48', is_abnormal: '1' },
      { item_name: 'MCV', item_value: '83', item_unit: 'fL', item_range: '82-98', is_abnormal: '0' },
      { item_name: 'RDW', item_value: '17.7', item_unit: '%', item_range: '10.5-15.5', is_abnormal: '1' },
      { item_name: 'White Blood Cells', item_value: '5.5', item_unit: 'K/uL', item_range: '4-11', is_abnormal: '0' },
      { item_name: 'Hemoglobin', item_value: '10.2', item_unit: 'g/dL', item_range: '12-16', is_abnormal: '1' },
      { item_name: 'Platelet Count', item_value: '271', item_unit: 'K/uL', item_range: '150-440', is_abnormal: '0' },
      { item_name: 'MCHC', item_value: '29.3', item_unit: '%', item_range: '31-35', is_abnormal: '1' },
      { item_name: 'PTT', item_value: '33.8', item_unit: 'sec', item_range: '25-36.5', is_abnormal: '0' },
      { item_name: 'INR(PT)', item_value: '2.2', item_unit: '', item_range: '0.9-1.1', is_abnormal: '1' },
      { item_name: 'PT', item_value: '23.6', item_unit: 'sec', item_range: '9.4-12.5', is_abnormal: '1' },
      { item_name: 'Bicarbonate', item_value: '36', item_unit: 'mEq/L', item_range: '22-32', is_abnormal: '1' },
      { item_name: 'Anion Gap', item_value: '10', item_unit: 'mEq/L', item_range: '8-20', is_abnormal: '0' },
      { item_name: 'Potassium', item_value: '3.7', item_unit: 'mEq/L', item_range: '3.3-5.1', is_abnormal: '0' },
      { item_name: 'Phosphate', item_value: '3.6', item_unit: 'mg/dL', item_range: '2.7-4.5', is_abnormal: '0' },
      { item_name: 'Glucose', item_value: '98', item_unit: 'mg/dL', item_range: '70-100', is_abnormal: '0' },
      { item_name: 'Sodium', item_value: '143', item_unit: 'mEq/L', item_range: '133-145', is_abnormal: '0' },
      { item_name: 'Calcium, Total', item_value: '8.6', item_unit: 'mg/dL', item_range: '8.4-10.3', is_abnormal: '0' },
      { item_name: 'Urea Nitrogen', item_value: '18', item_unit: 'mg/dL', item_range: '6-20', is_abnormal: '0' },
      { item_name: 'Magnesium', item_value: '2', item_unit: 'mg/dL', item_range: '1.6-2.6', is_abnormal: '0' },
      { item_name: 'Creatinine', item_value: '0.9', item_unit: 'mg/dL', item_range: '0.4-1.1', is_abnormal: '0' },
      { item_name: 'Chloride', item_value: '101', item_unit: 'mEq/L', item_range: '96-108', is_abnormal: '0' },
    ],
  },
  {
    image: 'mimic-10003400|20214994|2137-03-04 16:36:00',
    kind: 'US hospital panel',
    items: [
      { item_name: 'Sodium', item_value: '142', item_unit: 'mEq/L', item_range: '133-145', is_abnormal: '0' },
      { item_name: 'Creatinine', item_value: '0.6', item_unit: 'mg/dL', item_range: '0.4-1.1', is_abnormal: '0' },
      { item_name: 'Glucose', item_value: '138', item_unit: 'mg/dL', item_range: '70-100', is_abnormal: '1' },
      { item_name: 'Calcium, Total', item_value: '8.2', item_unit: 'mg/dL', item_range: '8.4-10.3', is_abnormal: '1' },
      { item_name: 'Urea Nitrogen', item_value: '16', item_unit: 'mg/dL', item_range: '6-20', is_abnormal: '0' },
      { item_name: 'Anion Gap', item_value: '9', item_unit: 'mEq/L', item_range: '8-20', is_abnormal: '0' },
      { item_name: 'Potassium', item_value: '3.7', item_unit: 'mEq/L', item_range: '3.3-5.1', is_abnormal: '0' },
      { item_name: 'Bicarbonate', item_value: '31', item_unit: 'mEq/L', item_range: '22-32', is_abnormal: '0' },
      { item_name: 'Chloride', item_value: '106', item_unit: 'mEq/L', item_range: '96-108', is_abnormal: '0' },
      { item_name: 'Phosphate', item_value: '1.9', item_unit: 'mg/dL', item_range: '2.7-4.5', is_abnormal: '1' },
      { item_name: 'Magnesium', item_value: '1.8', item_unit: 'mg/dL', item_range: '1.6-2.6', is_abnormal: '0' },
    ],
  },
  {
    image: 'mimic-10038081|20755971|2115-10-01 17:10:00',
    kind: 'US hospital panel',
    items: [
      { item_name: 'Troponin T', item_value: '0.02', item_unit: 'ng/mL', item_range: '0-0.01', is_abnormal: '1' },
      { item_name: 'Calcium, Total', item_value: '9.9', item_unit: 'mg/dL', item_range: '8.4-10.3', is_abnormal: '0' },
      { item_name: 'Creatinine', item_value: '0.9', item_unit: 'mg/dL', item_range: '0.4-1.1', is_abnormal: '0' },
      { item_name: 'Phosphate', item_value: '3.4', item_unit: 'mg/dL', item_range: '2.7-4.5', is_abnormal: '0' },
      { item_name: 'Chloride', item_value: '89', item_unit: 'mEq/L', item_range: '96-108', is_abnormal: '1' },
      { item_name: 'Urea Nitrogen', item_value: '25', item_unit: 'mg/dL', item_range: '6-20', is_abnormal: '1' },
      { item_name: 'Magnesium', item_value: '2.4', item_unit: 'mg/dL', item_range: '1.6-2.6', is_abnormal: '0' },
      { item_name: 'Glucose', item_value: '184', item_unit: 'mg/dL', item_range: '70-100', is_abnormal: '1' },
      { item_name: 'Bicarbonate', item_value: '20', item_unit: 'mEq/L', item_range: '22-32', is_abnormal: '1' },
      { item_name: 'Sodium', item_value: '124', item_unit: 'mEq/L', item_range: '133-145', is_abnormal: '1' },
      { item_name: 'Potassium', item_value: '6.2', item_unit: 'mEq/L', item_range: '3.3-5.1', is_abnormal: '1' },
      { item_name: 'Anion Gap', item_value: '21', item_unit: 'mEq/L', item_range: '8-20', is_abnormal: '1' },
      { item_name: 'RDW-SD', item_value: '69.9', item_unit: 'fL', item_range: '35.1-46.3', is_abnormal: '1' },
      { item_name: 'Hematocrit', item_value: '26', item_unit: '%', item_range: '34-45', is_abnormal: '1' },
      { item_name: 'Hemoglobin', item_value: '8.5', item_unit: 'g/dL', item_range: '11.2-15.7', is_abnormal: '1' },
      { item_name: 'Red Blood Cells', item_value: '2.71', item_unit: 'm/uL', item_range: '3.9-5.2', is_abnormal: '1' },
      { item_name: 'MCH', item_value: '31.4', item_unit: 'pg', item_range: '26-32', is_abnormal: '0' },
      { item_name: 'Platelet Count', item_value: '35', item_unit: 'K/uL', item_range: '150-400', is_abnormal: '1' },
      { item_name: 'MCHC', item_value: '32.7', item_unit: 'g/dL', item_range: '32-37', is_abnormal: '0' },
      { item_name: 'White Blood Cells', item_value: '2.7', item_unit: 'K/uL', item_range: '4-10', is_abnormal: '1' },
      { item_name: 'MCV', item_value: '96', item_unit: 'fL', item_range: '82-98', is_abnormal: '0' },
      { item_name: 'RDW', item_value: '20', item_unit: '%', item_range: '10.5-15.5', is_abnormal: '1' },
    ],
  },
  {
    image: 'mimic-10037861|24540843|2117-03-17 03:23:00',
    kind: 'US hospital panel',
    items: [
      { item_name: 'Specimen Type', item_value: 'ART.', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Base Excess', item_value: '0', item_unit: 'mEq/L', item_range: '', is_abnormal: '0' },
      { item_name: 'Calculated Total CO2', item_value: '23', item_unit: 'mEq/L', item_range: '21-30', is_abnormal: '0' },
      { item_name: 'Free Calcium', item_value: '1.1', item_unit: 'mmol/L', item_range: '1.12-1.32', is_abnormal: '1' },
      { item_name: 'Lactate', item_value: '1.3', item_unit: 'mmol/L', item_range: '0.5-2', is_abnormal: '0' },
      { item_name: 'pO2', item_value: '94', item_unit: 'mm Hg', item_range: '85-105', is_abnormal: '0' },
      { item_name: 'pH', item_value: '7.47', item_unit: 'units', item_range: '7.35-7.45', is_abnormal: '1' },
      { item_name: 'pCO2', item_value: '31', item_unit: 'mm Hg', item_range: '35-45', is_abnormal: '1' },
    ],
  },
  {
    image: 'mimic-10014354|29780751|2147-11-27 00:00:00',
    kind: 'US hospital panel',
    items: [
      { item_name: 'Chloride', item_value: '102', item_unit: 'mEq/L', item_range: '96-108', is_abnormal: '0' },
      { item_name: 'L', item_value: '28', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'H', item_value: '2', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'Anion Gap', item_value: '17', item_unit: 'mEq/L', item_range: '8-20', is_abnormal: '0' },
      { item_name: 'Bicarbonate', item_value: '24', item_unit: 'mEq/L', item_range: '22-32', is_abnormal: '0' },
      { item_name: 'Glucose', item_value: '265', item_unit: 'mg/dL', item_range: '70-100', is_abnormal: '1' },
      { item_name: 'Sodium', item_value: '139', item_unit: 'mEq/L', item_range: '133-145', is_abnormal: '0' },
      { item_name: 'Potassium', item_value: '4', item_unit: 'mEq/L', item_range: '3.3-5.1', is_abnormal: '0' },
      { item_name: 'Magnesium', item_value: '1.9', item_unit: 'mg/dL', item_range: '1.6-2.6', is_abnormal: '0' },
      { item_name: 'Phosphate', item_value: '4.2', item_unit: 'mg/dL', item_range: '2.7-4.5', is_abnormal: '0' },
      { item_name: 'Urea Nitrogen', item_value: '7', item_unit: 'mg/dL', item_range: '6-20', is_abnormal: '0' },
      { item_name: 'Calcium, Total', item_value: '8.1', item_unit: 'mg/dL', item_range: '8.4-10.3', is_abnormal: '1' },
      { item_name: 'Creatinine', item_value: '0.9', item_unit: 'mg/dL', item_range: '0.5-1.2', is_abnormal: '0' },
      { item_name: 'I', item_value: '0', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'MCV', item_value: '86', item_unit: 'fL', item_range: '82-98', is_abnormal: '0' },
      { item_name: 'Hemoglobin', item_value: '7.7', item_unit: 'g/dL', item_range: '13.7-17.5', is_abnormal: '1' },
      { item_name: 'White Blood Cells', item_value: '36.9', item_unit: 'K/uL', item_range: '4-10', is_abnormal: '1' },
      { item_name: 'Platelet Count', item_value: '113', item_unit: 'K/uL', item_range: '150-400', is_abnormal: '1' },
      { item_name: 'Hematocrit', item_value: '24.5', item_unit: '%', item_range: '40-51', is_abnormal: '1' },
      { item_name: 'RDW', item_value: '20.4', item_unit: '%', item_range: '10.5-15.5', is_abnormal: '1' },
      { item_name: 'MCHC', item_value: '31.4', item_unit: 'g/dL', item_range: '32-37', is_abnormal: '1' },
      { item_name: 'MCH', item_value: '27.1', item_unit: 'pg', item_range: '26-32', is_abnormal: '0' },
      { item_name: 'Red Blood Cells', item_value: '2.84', item_unit: 'm/uL', item_range: '4.6-6.1', is_abnormal: '1' },
      { item_name: 'RDW-SD', item_value: '61.6', item_unit: 'fL', item_range: '35.1-46.3', is_abnormal: '1' },
    ],
  },
  {
    image: 'mimic-10023771|20044587|2113-08-26 12:05:00',
    kind: 'US hospital panel',
    items: [
      { item_name: 'Chloride', item_value: '109', item_unit: 'mEq/L', item_range: '96-108', is_abnormal: '1' },
      { item_name: 'Sodium', item_value: '141', item_unit: 'mEq/L', item_range: '133-145', is_abnormal: '0' },
      { item_name: 'Potassium', item_value: '4', item_unit: 'mEq/L', item_range: '3.3-5.1', is_abnormal: '0' },
      { item_name: 'Glucose', item_value: '111', item_unit: 'mg/dL', item_range: '70-100', is_abnormal: '1' },
      { item_name: 'Magnesium', item_value: '2.2', item_unit: 'mg/dL', item_range: '1.6-2.6', is_abnormal: '0' },
      { item_name: 'Platelet Count', item_value: '169', item_unit: 'K/uL', item_range: '150-440', is_abnormal: '0' },
      { item_name: 'MCV', item_value: '91', item_unit: 'fL', item_range: '82-98', is_abnormal: '0' },
      { item_name: 'MCHC', item_value: '34.9', item_unit: '%', item_range: '31-35', is_abnormal: '0' },
      { item_name: 'White Blood Cells', item_value: '6', item_unit: 'K/uL', item_range: '4-11', is_abnormal: '0' },
      { item_name: 'MCH', item_value: '31.8', item_unit: 'pg', item_range: '27-32', is_abnormal: '0' },
      { item_name: 'Hematocrit', item_value: '25.2', item_unit: '%', item_range: '40-52', is_abnormal: '1' },
      { item_name: 'Red Blood Cells', item_value: '2.77', item_unit: 'm/uL', item_range: '4.6-6.2', is_abnormal: '1' },
      { item_name: 'Hemoglobin', item_value: '8.8', item_unit: 'g/dL', item_range: '14-18', is_abnormal: '1' },
      { item_name: 'RDW', item_value: '13.9', item_unit: '%', item_range: '10.5-15.5', is_abnormal: '0' },
    ],
  },
  {
    image: 'mimic-10002428||2156-10-29 11:48:00',
    kind: 'US hospital panel',
    items: [
      { item_name: 'Hematocrit', item_value: '32.7', item_unit: '%', item_range: '36-48', is_abnormal: '1' },
      { item_name: 'Urea Nitrogen', item_value: '28', item_unit: 'mg/dL', item_range: '6-20', is_abnormal: '1' },
      { item_name: 'Bicarbonate', item_value: '33', item_unit: 'mEq/L', item_range: '22-32', is_abnormal: '1' },
      { item_name: 'Thyroid Stimulating Hormone', item_value: '5.3', item_unit: 'uIU/mL', item_range: '0.27-4.2', is_abnormal: '1' },
      { item_name: 'MCV', item_value: '93', item_unit: 'fL', item_range: '82-98', is_abnormal: '0' },
      { item_name: 'Chloride', item_value: '98', item_unit: 'mEq/L', item_range: '96-108', is_abnormal: '0' },
      { item_name: 'MCH', item_value: '30.6', item_unit: 'pg', item_range: '27-32', is_abnormal: '0' },
      { item_name: 'Sodium', item_value: '135', item_unit: 'mEq/L', item_range: '133-145', is_abnormal: '0' },
      { item_name: 'White Blood Cells', item_value: '9.2', item_unit: 'K/uL', item_range: '4-11', is_abnormal: '0' },
      { item_name: 'Anion Gap', item_value: '9', item_unit: 'mEq/L', item_range: '8-20', is_abnormal: '0' },
      { item_name: 'Red Blood Cells', item_value: '3.53', item_unit: 'm/uL', item_range: '4.2-5.4', is_abnormal: '1' },
      { item_name: 'Creatinine', item_value: '0.7', item_unit: 'mg/dL', item_range: '0.4-1.1', is_abnormal: '0' },
      { item_name: 'Platelet Count', item_value: '296', item_unit: 'K/uL', item_range: '150-440', is_abnormal: '0' },
      { item_name: 'Hemoglobin', item_value: '10.8', item_unit: 'g/dL', item_range: '12-16', is_abnormal: '1' },
      { item_name: 'Potassium', item_value: '5.1', item_unit: 'mEq/L', item_range: '3.3-5.1', is_abnormal: '0' },
      { item_name: 'RDW', item_value: '14.8', item_unit: '%', item_range: '10.5-15.5', is_abnormal: '0' },
      { item_name: 'Estimated GFR (MDRD equation)', item_value: '', item_unit: '', item_range: '', is_abnormal: '0' },
      { item_name: 'MCHC', item_value: '33.1', item_unit: '%', item_range: '31-35', is_abnormal: '0' },
    ],
  },
];
